### ISSUE TITLE
Incompatible with newest Ad Astra Alpha

### ISSUE THREAD

**Issue by DaddySpin** [JDKDigital/noflyzone#1]
Using the new Ad Astra Alpha and when I spawn in my world and move it instantly crashes and the crash report looks like its trying to stop the jet suit from flying.

[crash-2024-01-18_11.06.28-client.txt](https://github.com/JDKDigital/noflyzone/files/13979699/crash-2024-01-18_11.06.28-client.txt)

**Comment by JaisDK** [comment]
https://www.curseforge.com/minecraft/mc-mods/no-fly-zone/files/5044937
