### ISSUE TITLE
[Feature Request] Way to enable flight in dimensions on a per player basis per dimension.

### ISSUE THREAD

**Issue by CanvasofSpores** [JDKDigital/noflyzone#2]
Given that the mod is primarily used in modpacks to stop players from breaking progression in certain dimensions, It'd be nice to have a way for pack devs to give players a way to enable flight in certain dimensions after they've gone through the progression of that dimension. 

My idea for this would be to have the mod check for a player attribute that is toggled off for any dimensions the player can't fly in, and have a consumable item that sets this attribute to true on the player for that dimension, based on a tag on the item itself.

Given that modpack devs already have the tools to edit drop tables and recipes with items having certain nbt tags, his would allow pack devs to add this item to say, the final boss of the twilight forest, or as a quest reward at the end of the progression for a mod, or a custom end-game crafting recipe, etc. It would also solve the initial problem of flight breaking progression, but giving the option to allow players to have flight in that dimension once they've completed that progression.

**Comment by JaisDK** [comment]
This is already supported through game stages (the mod)

**Comment by CanvasofSpores** [comment]
Oh, I didn't realize that. I'll close this issue in that case.
