### ISSUE TITLE
Crashes with Ad Astra 1.20.1

### ISSUE THREAD

**Issue by Joshernoob** [JDKDigital/noflyzone#3]
Making a new modpack and added this mod in to prevent fling in dims like Ad Astra plants and both mods load up just fine but as soon as i load a world it crashes with 
https://pastebin.com/ErHV1Hzy

as the code shows it crashes with a Ticking entity the SpaceSuitItem at first but when look closer, see that itdo to no fly taking over the player and the SpaceSuitItem not being able to see said player (Jetsuit)

**Comment by Joshernoob** [comment]
Edit: backtracking one version lets me get into the world but from looking at old reports it most likly won't fix the bug fully

**Comment by JaisDK** [comment]
Latest version of no fly zone only works with the latest alpha version of ad astra where they changed a lot of things. It says that in the release notes too.

**Comment by Joshernoob** [comment]
Will try once i Have the free time and report here to see if everything working

**Comment by Joshernoob** [comment]
From testing Seems it works on the version Ad Astra 1.15.10 Alpha as stated but nothing above like it says in the changelogs, i tryed 3 Alpha Ad astra versions 2 crashed do to there own reasons and the third had the same problem I made this for.

On top of that there are now 2 new beta verions Ad Astra 1.15.16 Beta and Ad Astra 1.15.15 Beta that do the same crash with jetpack problem that seem to be the newest updates

**Comment by JaisDK** [comment]
1.15.16 works fine for me, can you send the crash report to make sure it's the same problem?

**Comment by Joshernoob** [comment]
Will remake the problem and send it over, it may be one of the extra plant mods for Ad Astra thats doing it

**Comment by Joshernoob** [comment]
sorry fpr the delay, only have set day i can work my my pack. but anyway seems it was a moon addon that was making it happen and its not the jetpack so it may not be this mod doing it

**Comment by Joshernoob** [comment]
I know its been about a month since I updated this, but with other things and working on parts of the pack it got pushed to the side

anyway, I finally tested to see if the addons I have were the reason and seems they are not, however I have a feeling that it may be the world type mod i have Botania: Garden of Glass (untested)

**Comment by JaisDK** [comment]
the original crash log you sent is simply a mismatch between the version of ad astra and no-fly zone

could you please update both to latest and send a new crash report

**Comment by Joshernoob** [comment]
updated to the newest beta and newest beta of Ad Astra: Giselle Addon and that seems to fixx it, seems Ad Astra: Giselle Addon messes with the jetpack as well
